In [ ]:
#  Nama: Julius Satria Agung
#  NRP: 152024049
#  Kelas: BB

import pandas as pd

data = {
        'Nama': ['John', 'Jane', 'Bob', 'Alice'],
        'Usia': [25, 35, 30, 28],
        'Gaji': [50000, 60000, 70000, 55000]
}

df = pd.DataFrame(data)

In [74]:
gaji_baru = []
kenaikan_gaji = lambda gaji: gaji * 1.05

for gaji in df['Gaji']:
        gaji_baru.append(kenaikan_gaji(gaji))
            

df['Gaji kenaikan'] = gaji_baru
df

#pertama kita buat yang namanya list di variabel gaji_baru untuk menyimpann nilai data gaji baru, yang sudah di naikan sebesar 5% dengan perulangan menggunakan fungsi lambda.
#setelah itu, kita panggil dataframe['Gaji] lalu masukan kedalamnya menggunakan variabel list gaji_baru

    Nama  Usia   Gaji  Gaji kenaikan
0   John    25  50000        52500.0
1   Jane    35  60000        63000.0
2    Bob    30  70000        73500.0
3  Alice    28  55000        57750.0

In [ ]:
gaji_final = []
kenaikan_gaji_30 = lambda gaji: gaji * 1.02

for i in range(len(df)):
    gaji_sekarang = df.loc[i, 'Gaji kenaikan']
    usia = df.loc[i, 'Usia']
    
    if usia > 30:
        gaji_final.append(kenaikan_gaji_30(gaji_sekarang))
    else:
        gaji_final.append(gaji_sekarang)
        
df['Gaji final'] = gaji_final
df

# sama seperti sebelumnya seperti kenaikan lagi tapi untuk usia diatas 30. dengan menggunakan len(df) untuk looping sampai panjang df
# lalu kita panggil df.loc[i, 'Gaji kenaikan'] untuk mengambil gaji yang sudah di naikan 5% sebelumnya
# lalu kita panggil df.loc[i, 'Usia'] untuk mengambil usia
# setelah itu kita buat kondisi if usia > 30 maka gaji akan di naikan 2% lagi dengan fungsi lambda

    Nama  Usia   Gaji  Gaji kenaikan  Gaji final
0   John    25  50000        52500.0     52500.0
1   Jane    35  60000        63000.0     64260.0
2    Bob    30  70000        73500.0     73500.0
3  Alice    28  55000        57750.0     57750.0